### ISSUE TITLE
ServiceAccount integration for AWS

### ISSUE THREAD

**Issue by phanimullapudi** [crossplaneio/stack-aws#109]
### What problem are you facing?

Currently we are unable to create RDS instances using the crossplane. Due to security restrictions we are only allowed or restricted to use ServiceAccounts. 

### How could Crossplane help solve your problem?

Ability to support ServiceAccount by using annotations or some other way will avoid using AWS credentials manually.

**Comment by negz** [comment]
Thanks for raising this issue @phanimullapudi!

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

It sounds like what you want to do is leverage the above EKS functionality such that Crossplane can use an IAM role associated with a Kubernetes `ServiceAccount`, instead of using an IAM role whose access token is stored in a Kubernetes `Secret`?

It's possible we could enable this by:

1. Adding a field to the existing AWS provider that instructs the `stack-aws` binary to fall back to using web identity tokens per https://github.com/aws/aws-sdk-go/pull/2667.
1. Update all managed resource controllers to respect said field.
1. Documenting how to setup the stack-aws deployment to use service account based IAM roles ala https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-cni-walkthrough.html (and/or automating it in our Helm chart).

**Comment by negz** [comment]
This is very closely related to https://github.com/crossplaneio/stack-aws/issues/110.

**Comment by phanimullapudi** [comment]
Our current EKS stack is configured to use IAM roles using OIDC. The mentioned above way looks reasonable for me.

**Comment by negz** [comment]
Cross linking another related issue: https://github.com/crossplaneio/crossplane-runtime/issues/101

**Comment by hasheddan** [comment]
Providing an update here. We currently use `aws-sdk-go-v2` across `stack-aws` and unfortunately this functionality has not been implemented on `v2`: https://github.com/aws/aws-sdk-go-v2/issues/475

I have successfully deployed `stack-aws` in an EKS cluster using IAM roles for `ServiceAccount`, and that is working well, it is just consuming the credentials that is a bit more of a hurdle. I believe we can manually assume the role using the `sts` client, but I will also investigate if I can provide a simple upstream fix to the issue referenced above.
